### ISSUE TITLE
[Bug]: Update plan when pressing Enter key from input fields

### ISSUE THREAD

**Issue by Andreasgdp** [Andreasgdp/Wishing-Plan#33]
### Actual behaviour

When changing values of input fields in Plan settings, the plan does not update, when enter key is pressed. 

The plan can only be updated by clicking the "Update" button.

### Expected behaviour

When editing the input fields of plan settings, pressing Enter key on keyboard should result in the plan being updated with the current state of plan settings.

### Steps to reproduce

1. Go to plan page
2. Edit input fields on left hand side
3. Try to press the enter key from within an input
4. See that nothing happens

### What platform you are seeing the problem on

All Platforms

### Attatchments

![firefox_FS1KhmqweI](https://user-images.githubusercontent.com/39928082/213715730-6367bb15-051c-4ffc-8bfa-48add3842ae4.gif)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andreasgdp** [comment]
This would be a good place to start: https://github.com/Andreasgdp/Wishing-Plan/blob/master/src/components/screens/Plan/PlanSidebar.tsx#LL116C7-L127C21

**Comment by RehkMansa** [comment]
Hello, is this task still open and can i take it on. Ps this is my first attempt at opensource, so go easy on me

**Comment by Andreasgdp** [comment]
@RehkMansa Yes, this bug has not yet been addressed, so your help is greatly appreciated 😁

**Comment by RehkMansa** [comment]
Help needed, I'm trying to setup discord to sign in and create an account(it seems the easiest). What's the redirect url supposed to be
