### ISSUE TITLE
[Feature]:  Add commit precommit hooks and linting rules

### ISSUE THREAD

**Issue by RehkMansa** [Andreasgdp/Wishing-Plan#36]
### Is your feature request related to a problem? Please describe

Its not really much of a problem, I just think it would be cool if we had linting rules and maybe a prettier config setup along with husky's precommit hook, also lintstaged, I know the list is long, but that way, it would be easy catch issues like console.log, unused vars etc.

### Describe the solution you'd like

Setup husky, eslint, prettier, and lint-staged to check files before commit

### Describe alternatives you've considered

Maybe server side or pipeline validation that checks the code for lint errors, i think they already exist

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Andreasgdp** [comment]
I agree with some of the ideas like adding a linting setup and a prettier setup, but pre-commit hooks I don't agree with.

I agree with the statements Theo explains about pre-commit hooks in this video.
https://youtu.be/RAelLqnnOp0

So @RehkMansa If you could describe another issue describing the addition of a linting setup, prettier setup (and possibly other checks you might think would be nice to have as a developer).
These setups would then be integrated into our pipelines afterwards.

This means for a new contribution the developer will be able to do all the checks locally, and when he/she feels confident enough, open a PR, where these checks will be run as part of the PR and be required before merge.

**Comment by Andreasgdp** [comment]
On further consideration, we don't need to create a new issue on this. I am working on implementing the elements discussed here, and they will be in soon.

@RehkMansa Thanks for the interest and engagement.

**Comment by Andreasgdp** [comment]
It wasn't my intention; however, as my addition will only be adding Prettier and Linting, you could see if other checks are relevant.

At some point we will want to add testing to the pipeline as well.

**Comment by RehkMansa** [comment]
Sorry I missed out on this convo, thanks for approving the feature :)
