### ISSUE TITLE
[Bug]: Plan sidebar number input shows NaN

### ISSUE THREAD

**Issue by Andreasgdp** [Andreasgdp/Wishing-Plan#64]
### Actual behaviour

When entering a negative number in the input fields in plan sidebar (AMOUNT SAVED and AMOUNT TO SAVE) the fields show NaN.

### Expected behaviour

- The user should be able to input a negative value in amount saved
  - This is of different reasons e.g., debt.
- AMOUNT TO SAVE should be lower clamped to 0 i.e., the lowest value the user is able to put in is 0.

### Steps to reproduce

1. Go to a plan
2. Try to enter a negative number
3. See "NaN"

### What platform you are seeing the problem on

All Platforms

### Attatchments

[Screencast from 02-14-2023 02:58:17 PM.webm](https://user-images.githubusercontent.com/39928082/218759367-fb6b0351-04fb-4422-b0df-aed1c5490260.webm)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by oraliahdz** [comment]
Hi, would like to help with this

**Comment by Andreasgdp** [comment]
@oraliahdz Your help is welcome 😄

**Comment by oraliahdz** [comment]
I think I'm doing somethig wrong, I can't sign in neither with google or discord

**Comment by Andreasgdp** [comment]
@oraliahdz You will have to add provider credentials for either discord or google (or both) to be able to sign in.
https://github.com/Andreasgdp/Wishing-Plan/blob/master/.env.example#L22

@RehkMansa also incountered an issue when setting authentication up, what he found may also help you
https://github.com/Andreasgdp/Wishing-Plan/issues/33

Perhaps we should consider adding standard Email & Password sign in, to make it easier for new contributors to get started.

Note: If you feel like something is missing from the getting started guide, you are welcome to make it more clear 😄
