### ISSUE TITLE
[GFI]: Show total cost of wishes in a plan

### ISSUE THREAD

**Issue by Andreasgdp** [Andreasgdp/Wishing-Plan#84]
### Description

Get the sum of all the prices of wishes in a plan and display the information in the sidebar.

![image](https://user-images.githubusercontent.com/39928082/221022454-63d9f0c9-dee3-4164-a6f7-281082a23b0c.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kunalkashyap855** [comment]
@Andreasgdp Hi there! I would like to work on this issue, can you please assign it to me? 
Also can you share how exactly you want the addition to look? Like, what should be the label text?

**Comment by Andreasgdp** [comment]
Cool! 
@kunalkashyap855 I would like just below the select the following:

- A devider (https://chakra-ui.com/docs/components/divider/usage)
- Label (same as the others - bold): **TOTAL COST**
- Tag (https://chakra-ui.com/docs/components/tag/usage): <sum_of_all_prices> <currency>
- Devider

Then the share functionality at the bottom still

**Comment by kunalkashyap855** [comment]
@Andreasgdp Understood! I'll get on it.

**Comment by kunalkashyap855** [comment]
@Andreasgdp I have opened a PR (#86 ) with code changes that fulfill the requirements. I have explained my changes with the PR along with a screenshot of the current result. I wanted to point out that I couldn't test the changes properly as I couldn't create a wish in the main plan screen. I was always getting the error 401 UNAUTHORIZED.

Please let me know what you think of my changes.

**Comment by Andreasgdp** [comment]
@kunalkashyap855 Hmm interesting... How did you sign in?
Have you tried signing out and back in?

If you are able to reproduce the problem, e.g., by cleaning the database, and trying again with signing in, you are welcome to create a bug on the issue 😁

I will have a look at your changes 👍

**Comment by kunalkashyap855** [comment]
> @kunalkashyap855 Hmm interesting... How did you sign in? Have you tried signing out and back in?
> 
> If you are able to reproduce the problem, e.g., by cleaning the database, and trying again with signing in, you are welcome to create a bug on the issue 😁
> 
> I will have a look at your changes 👍

@Andreasgdp I logged in with both gmail and discord and tried, but got the error both times. I'll try again after cleaning the database and if the issue persists, I'll create an issue for the same.
